source "https://rubygems.org"

# Khai báo gem cần thiết -> Dùng ở tat ca moi truong -> bundle install --without development test
gem "rails", "~> 7.0.0"
gem "pg", "~> 1.2" # PostgreSQL
gem "puma", "~> 6.0"

# Khai báo gem chỉ dùng trong môi trường phát triển
group :development do
  gem "pry"
end

# Khai báo gem chỉ dùng trong môi trường test
group :test do
  gem "rspec"
end
